### PR TITLE
Strings end with backslash bug fix, example "test\\"

### PR DESCRIPTION
**Pull request by magicops**

### CODE REVIEW

**Comment by magicops** [comment]
Please check the changes and merge if it is ok.
Can you tell me when do you release on Nuget?

**Comment by bijington** [comment]
Hi @magicops, thanks for the submission. Unfortunately it causes the `ShouldEscapeCharacters` unit test to fail so I cannot let this be merged.

Out of interest is this intended to fix #49? If so does that mean it is more urgent than I was expecting?

As mentioned in that linked issue I have a partial fix which can be tidied up if you do require a more urgent resolution to the issue. I do have an issue that escaped slashes themselves still come out as `\\` whereas they really should be returned as `\`.

**Comment by magicops** [comment]
Hi @bijington,
Thank you for the response. I didn't check other escapable characters such as \n, \t, etc., that's why the test was failed. I have updated the code and we should be good now.

The #49 is the same issue is mine and it turned out that @MichelR666 is my colleague who was working on this project before me :)

I have added a few lines into the ClearString method to return \ when there is \\ in the string which fixes the issue. Also, included \" to return ". In the ClearString method, it was just checking \n, \t, \r, and \'.

**Comment by bijington** [comment]
@magicops thanks for the update.

I unfortunately won't have time to review with what is left of today but I will plan to take a look at this tomorrow.

For what it is worth I do plan to rework this area to reduce complexity and improve on any issues like this but I will plan to make sure that this scenario is covered during that implementation. Obviously the rework will take a fair amount more time so I am happy to aim to merge this in and do a release to NuGet so that you can move on from the issue.

I will let you know tomorrow.

**Comment by magicops** [comment]
Thank you @bijington

**Pull request merged**
