### PR TITLE
use include

### PR DESCRIPTION
**Pull request by SimonCropp**
thoughts?

### CODE REVIEW

**Comment by bijington** [comment]
@SimonCropp my initial thoughts are that you are a very kind person to be offering this level of support :).

I will take a look at this later on this evening and play around with the output thank you.

**Comment by bijington** [comment]
Upon an actual investigation I think I could really get used to this approach!

One thing that would be nice (not sure if it is possible) is to define a single template file (e.g. `functions.include.md`) and then populate this multiple times. Although I suspect this would complicate things like build a Table of Contents, etc. I could live with having to create a separate template for each function though. In fact I could quite easily script the creation of those if needs be.

Thank you so much for this assistance!

**Comment by SimonCropp** [comment]
> One thing that would be nice (not sure if it is possible) is to define a single template file (e.g. functions.include.md) and then populate this multiple times. Although I suspect this would complicate things like build a Table of Contents, etc.

i think this should all work. give it a try

**Comment by bijington** [comment]
@SimonCropp sorry I really should have explained about the attempt I did try. I have pushed up what I tried which doesn't work but I am most likely not understanding this.

What I did was to create a single key: `Function` and then add 2 snippets that refer to this key. Is this how you would expect to achieve it?

**Comment by bijington** [comment]
As I mentioned before though this was a nice to have. I will dig deeper and see if I need to raise a feature request against your library.

Thank you again so much for the assistance in showing me how to use your library. I hope to repay you somehow!

**Comment by bijington** [comment]
@SimonCropp sorry I haven't got round to actioning this yet. I really do appreciate the effort you put in and will make use of it in the not so distant future

**Pull request closed without merging**
